- name: Create users
  hosts: "*"                                  # Specifies that the playbook will be applied to all servers
  tasks:
    - name: Create user for REDHAT OS FAMILY
      ansible.builtin.user:                   # for user creation task. It is used for the management of user accounts.
        name: "{{ item }}"
        state: present                        # They are created if the specified users do not exist.
      loop:
        - joe
        - matt
        - james
        - oliver
      when: ansible_os_family == "RedHat"     # Ensures that the task runs only when ansible_os_family is defined as "RedHat".

    - name: Create user for SUSE OS FAMILY
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - david
        - tyler
      when: ansible_os_family == "SUSE"

    - name: Create user for DEBIAN OS FAMILY
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - john
        - aaron
      when: ansible_os_family == "Debian" or ansible_distribution_version == "20.04"    # Makes it work if family is "Debian" or version "20.04"