- name: Remove Apache from webservers
  hosts: webservers
  tasks:
   - name: Remove Apache
     ansible.builtin.yum:
       name: httpd
       state: absent           # When set to "absent" the package is removed.
       autoremove: yes         # Ensures dependencies are automatically cleaned up after the parent package is uninstalled.

- name: Remove Apache from ubuntuservers
  hosts: ubuntuservers
  tasks:
   - name: Remove Apache
     ansible.builtin.apt:
       name: apache2
       state: absent
       autoremove: yes
       purge: yes          # the package's configuration files are also deleted