- name: create a user
  hosts: all
  become: true
  vars_files:
    - secret-1.yml
  tasks:
    - name: creating user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash ('sha512') }}"   # The content of the "password" variable is encrypted using the SHA-512 encryption method.
        