- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install yum-utils package
      ansible.builtin.yum:
        name: yum-utils
        state: latest

    - name: Download docker-ce.repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ansible.builtin.yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copy database file to postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/todo-app-pern/database
        dest: /home/ec2-user
      when: ansible_facts['default_ipv4']['address'] == "172.31.25.68"   # postgresql private address

    - name: Copy database file to postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/todo-app-pern/server
        dest: /home/ec2-user
      when: ansible_facts['default_ipv4']['address'] == "172.31.25.68"   # nodejs private address
      
    - name: Copy database file to postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/todo-app-pern/client
        dest: /home/ec2-user
      when: ansible_facts['default_ipv4']['address'] == "172.31.25.68"   # react private address
